version: 1
microservices:
  - name: sandbox-compiler-c
    directory: images/sandbox-compiler-c
  - name: sandbox-compiler-cpp
    directory: images/sandbox-compiler-cpp
  - name: sandbox-compiler-cs
    directory: images/sandbox-compiler-cs
  - name: sandbox-compiler-d
    directory: images/sandbox-compiler-d
  - name: sandbox-compiler-elixir
    directory: images/sandbox-compiler-elixir
  - name: sandbox-compiler-go
    directory: images/sandbox-compiler-go
  - name: sandbox-compiler-haskell
    directory: images/sandbox-compiler-haskell
  - name: sandbox-compiler-java
    directory: images/sandbox-compiler-java
  - name: sandbox-compiler-javascript
    directory: images/sandbox-compiler-javascript
  - name: sandbox-compiler-kotlin
    directory: images/sandbox-compiler-kotlin
  - name: sandbox-compiler-lua
    directory: images/sandbox-compiler-lua
  - name: sandbox-compiler-ocaml
    directory: images/sandbox-compiler-ocaml
  - name: sandbox-compiler-pascal
    directory: images/sandbox-compiler-pascal
  - name: sandbox-compiler-perl
    directory: images/sandbox-compiler-perl
  - name: sandbox-compiler-php
    directory: images/sandbox-compiler-php
  - name: sandbox-compiler-python3
    directory: images/sandbox-compiler-python3
  - name: sandbox-compiler-reason
    directory: images/sandbox-compiler-reason
  - name: sandbox-compiler-ruby
    directory: images/sandbox-compiler-ruby
  - name: sandbox-compiler-rust
    directory: images/sandbox-compiler-rust
  - name: sandbox-compiler-scala
    directory: images/sandbox-compiler-scala
  - name: sandbox-runtime-c
    directory: images/sandbox-runtime-c
  - name: sandbox-runtime-cpp
    directory: images/sandbox-runtime-cpp
  - name: sandbox-runtime-cs
    directory: images/sandbox-runtime-cs
  - name: sandbox-runtime-d
    directory: images/sandbox-runtime-d
  - name: sandbox-runtime-elixir
    directory: images/sandbox-runtime-elixir
  - name: sandbox-runtime-go
    directory: images/sandbox-runtime-go
  - name: sandbox-runtime-haskell
    directory: images/sandbox-runtime-haskell
  - name: sandbox-runtime-java
    directory: images/sandbox-runtime-java
  - name: sandbox-runtime-javascript
    directory: images/sandbox-runtime-javascript
  - name: sandbox-runtime-kotlin
    directory: images/sandbox-runtime-kotlin
  - name: sandbox-runtime-lua
    directory: images/sandbox-runtime-lua
  - name: sandbox-runtime-ocaml
    directory: images/sandbox-runtime-ocaml
  - name: sandbox-runtime-pascal
    directory: images/sandbox-runtime-pascal
  - name: sandbox-runtime-perl
    directory: images/sandbox-runtime-perl
  - name: sandbox-runtime-php
    directory: images/sandbox-runtime-php
  - name: sandbox-runtime-python3
    directory: images/sandbox-runtime-python3
  - name: sandbox-runtime-reason
    directory: images/sandbox-runtime-reason
  - name: sandbox-runtime-ruby
    directory: images/sandbox-runtime-ruby
  - name: sandbox-runtime-rust
    directory: images/sandbox-runtime-rust
  - name: sandbox-runtime-scala
    directory: images/sandbox-runtime-scala
environments: []
image_repository:
    project_id: riddles-microservices
    google_keys_path: "{{ DOCKER_IMAGE_REPOSITORY_CREDENTIALS_FILE }}"
